
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_INIT_SUCCESS = 'LOGIN_USER_INIT_SUCCESS';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const FETCH_THINGS_SUCCESS = 'FETCH_THINGS_SUCCESS';
export const FETCH_THING_SUCCESS = 'FETCH_THING_SUCCESS';

export const ADD_THING_FAILURE = 'ADD_THING_FAILURE';
